moordash:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: moordash
    username: root
    password: "root"
  alioss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    access-key-id:   # To wipe out before pushing to GitHub
    access-key-secret:   # To wipe out before pushing to GitHub
    bucket-name: moordash
  awsoss:
    access-key:
    secret-key:
    bucket-name: moordash-oss
    region: us-east-1
  redis:
    host: 192.168.8.128
    port: 6379
    password:
    database: 10
  wechat:
    appid: wx9e8dde9d2df9df58
    secret: 7a354c0cab2186281c18839acf453e37
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php